### ISSUE TITLE
Create tags for new releases

### ISSUE THREAD

**Issue by djmattyg007** [tkem/mopidy-podcast-itunes#11]
It seems a bit silly to navigate to the repository homepage and see that the latest release is "v1.0.0" from many years ago, when in fact there was a much more recently release.

**Comment by tkem** [comment]
There's a tag for v3.0.0 AFAICS, so I don't know what you're talking about, frankly...

**Comment by tkem** [comment]
Ok, I realized you probably mean the GitHub "Releases" page: https://github.com/tkem/mopidy-podcast-itunes/releases

I'm no longer using these, at least with Python projects, since they're pretty irrelevant. Proper releases of this package are published on PyPI, and are linked from the project's README. 

I should probably delete the initial entries on the GitHub Releases page to avoid confusion, though.

**Comment by tkem** [comment]
Done.
